#replace word in string  by number
word=input("enter the word:")
word=word.replace("a","4")
word=word .replace("b","8")
word=word.replace("e","3")
word=word.replace("l","1")
word=word.replace("o","0")
word=word.replace("s","5")
word=word.replace("t","7")
print(word)
